// ERRORS REDUCER
export const GET_ERRORS = "GET_ERRORS";

// AUTH REDUCER
export const AUTHORIZE_USER = "AUTHORIZE_USER"
export const SET_CURRENT_USER = "SET_CURRENT_USER";

//Profile Reducer
export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";